### ISSUE TITLE
Failed to install on Anaconda for Windows

### ISSUE THREAD

**Issue by dvchoo** [danielenricocahall/elephas#19]
**Describe the bug**
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "setup.py", line 5, in <module>
          long_description = (this_directory / "README.md").read_text()
        File "C:\Tools\Anaconda3\lib\pathlib.py", line 1267, in read_text
          return f.read()
        File "C:\Tools\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2458: character maps to <undefined>

**To Reproduce**
pip install elephas

**Expected behavior**
Installation successful

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context**
It seems like the README.md has UTF-8 character. Problem is fixed after adding UTF-8 encoding to line 5 in setup.py, i.e. 
long_description = (this_directory / "README.md").read_text(encoding="UTF-8")

**Comment by danielenricocahall** [comment]
Hello @dvchoo , thank you for bringing this to my attention! Try to install the latest version (3.4.8) and let me know if it's fixed.
